# Generated by Django 3.0.3 on 2020-07-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('lattitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('crime_type', models.TextField(max_length=32)),
            ],
        ),
    ]
